export const neighborhoodInfo: Record<string, string> = {
  "Allerton": "A quiet Bronx enclave developed in the 1920s, named after landowner John Jacob Allerton.",
  "Alley Pond Park": "Home to a 400-year-old tulip tree, one of the oldest living things in New York City.",
  "Annadale-Huguenot-Prince's Bay-Woodrow": "A rural-feeling corner of Staten Island where French Huguenot settlers arrived in the 1600s.",
  "Arden Heights-Rossville": "Site of a 19th-century shipbuilding community whose remains can still be found along the waterfront.",
  "Astoria (Central)": "Long the heart of NYC's Greek community, Astoria became a hub of Greek culture after WWII.",
  "Astoria (East)-Woodside (North)": "A diverse corridor shaped by waves of Irish, Greek, and South Asian immigration over decades.",
  "Astoria (North)-Ditmars-Steinway": "Named for the Steinway piano factory built here in 1871, which still operates today.",
  "Astoria Park": "The park's grand stone pool was built by the WPA in 1936 and is still in use.",
  "Auburndale": "A residential Queens neighborhood developed in the late 19th century as a streetcar suburb.",
  "Baisley Park": "The park sits near the childhood home of hip-hop legend 50 Cent in South Jamaica.",
  "Barren Island-Floyd Bennett Field": "NYC's first municipal airport opened here in 1931 and was used by aviator Amelia Earhart.",
  "Bath Beach": "A Brooklyn waterfront neighborhood that once featured grand Victorian bathhouses along the shore.",
  "Bay Ridge": "Norwegian and Scandinavian immigrants shaped this Brooklyn neighborhood's character in the early 1900s.",
  "Bay Terrace-Clearview": "A planned postwar community in northeastern Queens featuring some of the borough's most expansive homes.",
  "Bayside": "This Queens neighborhood was a popular resort destination for wealthy New Yorkers in the 1800s.",
  "Bedford Park": "Home to the New York Botanical Garden, one of the largest botanical gardens in the world.",
  "Bedford-Stuyvesant (East)": "Bed-Stuy is one of the largest predominantly Black communities in the United States.",
  "Bedford-Stuyvesant (West)": "The western half of Bed-Stuy contains some of Brooklyn's finest intact brownstone architecture.",
  "Bellerose": "A Queens neighborhood straddling the Nassau County border, known for its tight-knit community feel.",
  "Belmont": "Known as the Bronx's Little Italy, Arthur Avenue here rivals Manhattan's for authentic Italian food.",
  "Bensonhurst": "This Brooklyn neighborhood was immortalized in the 1977 film Saturday Night Fever, starring John Travolta.",
  "Borough Park": "One of the largest Orthodox Jewish communities in the world, with dozens of synagogues.",
  "Breezy Point-Belle Harbor-Rockaway Park-Broad Channel": "This barrier peninsula community was devastated by Hurricane Sandy in 2012 and has since rebuilt.",
  "Brighton Beach": "Known as Little Odessa, Brighton Beach became home to Russian and Eastern European immigrants in the 1970s.",
  "Bronx Park": "The park houses both the Bronx Zoo and the New York Botanical Garden within its borders.",
  "Brooklyn Heights": "The first NYC neighborhood designated a historic district in 1965, with stunning views of Manhattan.",
  "Brooklyn Navy Yard": "This 300-acre industrial complex built warships for the US Navy from the 1800s through WWII.",
  "Brownsville": "Birthplace of planned parenthood founder Margaret Sanger, who opened her first clinic here in 1916.",
  "Bushwick (East)": "A neighborhood with a long brewing history, once home to over 40 breweries in the 1800s.",
  "Bushwick (West)": "West Bushwick has become known for its vibrant street art scene and the annual Bushwick Collective.",
  "Calvary & Mount Zion Cemeteries": "Calvary Cemetery, founded in 1848, is one of the largest cemeteries in the United States.",
  "Calvert Vaux Park": "Named for the British architect who co-designed Central Park with Frederick Law Olmsted.",
  "Cambria Heights": "A middle-class Black community in Queens that flourished during the post-WWII migration from the South.",
  "Canarsie": "Originally a Lenape settlement, Canarsie was a fishing village long before Brooklyn was incorporated.",
  "Canarsie Park & Pier": "The pier offers sweeping views of Jamaica Bay and is a favorite spot for local anglers.",
  "Carroll Gardens-Cobble Hill-Gowanus-Red Hook": "Red Hook was once NYC's busiest cargo port before container shipping moved operations elsewhere in the 1950s.",
  "Castle Hill-Unionport": "A Bronx neighborhood shaped by Irish and Italian communities who settled here in the early 1900s.",
  "Central Park": "Designed by Olmsted and Vaux, Central Park was the first major landscaped public park in the US.",
  "Chelsea-Hudson Yards": "The High Line, a former elevated freight rail, was converted into a public park opening in 2009.",
  "Chinatown-Two Bridges": "One of the oldest and densest Chinatowns in the US, home to immigrants since the 1870s.",
  "Claremont Park": "A Bronx park built on rocky terrain that was too hilly to develop for housing.",
  "Claremont Village-Claremont (East)": "One of the Bronx's oldest neighborhoods, with deep roots in African American and Puerto Rican culture.",
  "Clinton Hill": "Pratt Institute, one of America's top art and design schools, has anchored this neighborhood since 1887.",
  "Co-op City": "Built in the late 1960s, Co-op City remains the largest cooperative housing complex in the world.",
  "College Point": "A peninsula community in Queens that was once a center for rubber and textile manufacturing.",
  "Concourse-Concourse Village": "The Grand Concourse, built in 1909, was modeled after the Champs-Élysées in Paris.",
  "Coney Island-Sea Gate": "Coney Island was America's most famous amusement destination in the early 20th century, drawing millions annually.",
  "Corona": "Louis Armstrong lived in Corona for nearly 30 years; his home is now a national historic site.",
  "Crotona Park": "The park's Indian Lake was created in the 1930s and became a beloved summer swimming spot.",
  "Crotona Park East": "A Bronx neighborhood that became the symbolic center of urban decay in the 1970s and 1980s.",
  "Crown Heights (North)": "Home to a large Caribbean community and the annual West Indian American Day Carnival parade.",
  "Crown Heights (South)": "The Brooklyn Children's Museum here, founded in 1899, was the first children's museum in the world.",
  "Cunningham Park": "One of Queens' largest parks, with over 300 acres of forest and recreational facilities.",
  "Cypress Hills": "A diverse Brooklyn neighborhood that straddles the border with Queens along Jamaica Avenue.",
  "Douglaston-Little Neck": "One of NYC's few remaining private communities, with streets maintained by a local homeowners association.",
  "Downtown Brooklyn-DUMBO-Boerum Hill": "DUMBO's cobblestone streets were once home to dozens of factories and warehouses in the industrial era.",
  "Dyker Beach Park": "The park's golf course, opened in 1935, is one of the most popular public courses in NYC.",
  "Dyker Heights": "Famous for its elaborate Christmas light displays, which draw thousands of visitors every December.",
  "East Elmhurst": "Home to LaGuardia Airport, this Queens neighborhood was also home to jazz legend Ella Fitzgerald.",
  "East Flatbush-Erasmus": "Erasmus Hall, founded in 1787, is one of the oldest secondary schools in the United States.",
  "East Flatbush-Farragut": "A Caribbean-influenced Brooklyn neighborhood named for Civil War Admiral David Farragut.",
  "East Flatbush-Remsen Village": "A residential neighborhood that developed rapidly after the arrival of the subway in the 1920s.",
  "East Flatbush-Rugby": "Known for its strong Haitian and West Indian community that shaped the neighborhood from the 1960s onward.",
  "East Flushing": "A transitional neighborhood between downtown Flushing's commercial district and quieter residential Queens.",
  "East Harlem (North)": "Known as El Barrio, this neighborhood has been a center of Puerto Rican culture since the 1950s.",
  "East Harlem (South)": "The southern edge of El Barrio, home to vibrant street murals celebrating Latino heritage.",
  "East Midtown-Turtle Bay": "The United Nations headquarters has occupied this stretch of Midtown since opening in 1952.",
  "East New York (North)": "One of Brooklyn's most resilient communities, shaped by African American and Caribbean immigrant culture.",
  "East New York-City Line": "The neighborhood bordering Queens was one of the first NYC communities to experience urban renewal efforts.",
  "East New York-New Lots": "New Lots was an independent village before being annexed by Brooklyn in 1886.",
  "East Village": "The East Village was the epicenter of New York's punk and counterculture movements in the 1970s.",
  "East Williamsburg": "A transitional neighborhood between Bushwick and Williamsburg with deep roots in manufacturing.",
  "Eastchester-Edenwald-Baychester": "One of the northernmost communities in the Bronx, developed as a suburban retreat in the early 1900s.",
  "Elmhurst": "One of the most ethnically diverse neighborhoods on earth, with over 120 languages spoken by residents.",
  "Far Rockaway-Bayswater": "The westernmost tip of the Rockaways, with a historic Jewish community dating to the late 1800s.",
  "Ferry Point Park-St. Raymond Cemetery": "Ferry Point Park offers sweeping views of the Whitestone and Throggs Neck bridges.",
  "Financial District-Battery Park City": "The site of the original Dutch settlement of New Amsterdam, founded in 1626 at the island's tip.",
  "Flatbush": "Originally a Dutch colonial town, Flatbush was an independent municipality until annexed by Brooklyn in 1894.",
  "Flatbush (West)-Ditmas Park-Parkville": "Ditmas Park contains one of NYC's best-preserved collections of Victorian houses from the early 1900s.",
  "Flatlands": "One of the original six towns of Brooklyn, settled by Dutch colonists in the 1630s.",
  "Flushing Meadows-Corona Park": "Host of the 1939 and 1964 World's Fairs, this park is Queens' largest green space.",
  "Flushing-Willets Point": "Downtown Flushing is home to one of the largest Asian commercial districts outside of Asia.",
  "Fordham Heights": "Home to Fordham University, one of the oldest Catholic universities in the northeastern United States.",
  "Forest Hills": "The West Side Tennis Club here hosted the US Open tennis championships from 1915 to 1978.",
  "Forest Park": "A 538-acre Queens park featuring ancient glacial terrain and some of the borough's oldest trees.",
  "Fort Greene": "The neighborhood's park holds the Prison Ship Martyrs Monument, honoring thousands who died in British captivity.",
  "Fort Hamilton": "The oldest active military installation in New York, with roots going back to the War of 1812.",
  "Fort Totten": "A former Civil War-era fort that protected the entrance to Long Island Sound from enemy ships.",
  "Fort Wadsworth": "Guarding the Narrows since colonial times, Fort Wadsworth is one of the oldest military sites in the US.",
  "Fresh Meadows-Utopia": "A planned postwar community built in 1947 on the former site of the Fresh Meadows Country Club.",
  "Freshkills Park (North)": "Once the world's largest landfill, Freshkills is being transformed into a park three times the size of Central Park.",
  "Freshkills Park (South)": "The southern section of the Freshkills transformation project will eventually feature wetlands and recreational areas.",
  "Glen Oaks-Floral Park-New Hyde Park": "A quiet northeastern Queens neighborhood bordering Nassau County with a strong suburban character.",
  "Glendale": "A working-class Queens neighborhood with deep roots in German and Irish immigrant communities.",
  "Gramercy": "Gramercy Park is the only private park in Manhattan, accessible only to residents with a key.",
  "Grasmere-Arrochar-South Beach-Dongan Hills": "South Beach was once a fashionable resort destination with grand hotels lining the Staten Island shoreline.",
  "Gravesend (East)-Homecrest": "Gravesend was founded in 1645 by Lady Deborah Moody, one of America's first female colonial leaders.",
  "Gravesend (South)": "The southern section of one of Brooklyn's oldest settlements, with streets still following the original colonial grid.",
  "Gravesend (West)": "Home to a large community of Sephardic Jewish immigrants who arrived from Syria and Lebanon.",
  "Great Kills Park": "Part of the Gateway National Recreation Area, offering beaches and trails along Staten Island's southern shore.",
  "Great Kills-Eltingville": "A residential Staten Island community that developed rapidly after the opening of the Verrazzano Bridge in 1964.",
  "Green-Wood Cemetery": "Founded in 1838, Green-Wood is a National Historic Landmark where luminaries like Leonard Bernstein are buried.",
  "Greenpoint": "Brooklyn's northernmost neighborhood was once the site of the nation's largest oil refinery in the 1800s.",
  "Greenwich Village": "The Village has been a haven for artists, writers, and LGBTQ+ New Yorkers for over a century.",
  "Hamilton Heights-Sugar Hill": "Sugar Hill was home to jazz and Harlem Renaissance legends including Duke Ellington and Thurgood Marshall.",
  "Harlem (North)": "The northernmost stretch of Harlem, shaped by African American migration from the South beginning in the 1900s.",
  "Harlem (South)":"The Apollo Theater on 125th Street has launched the careers of countless music legends since 1934.",
  "Hart Island": "NYC's public cemetery since 1869, Hart Island contains the largest publicly funded cemetery in the world.",
  "Hell's Kitchen": "Once one of NYC's most dangerous neighborhoods, Hell's Kitchen was named for its brutal tenement conditions.",
  "Highbridge": "Home to the oldest standing bridge in NYC, the High Bridge aqueduct was built in 1848.",
  "Highbridge Park": "The park runs along the Harlem River and contains the historic High Bridge water tower.",
  "Highland Park-Cypress Hills Cemeteries (North)": "A neighborhood defined by the sweeping Highland Park ridgeline and historic cemetery grounds.",
  "Highland Park-Cypress Hills Cemeteries (South)": "The cemeteries here include the resting places of numerous Civil War veterans and notable New Yorkers.",
  "Hoffman & Swinburne Islands": "Artificial islands built in the 1870s to quarantine immigrants with infectious diseases arriving by ship.",
  "Hollis": "Hollis is widely considered the birthplace of hip-hop, home to Run-DMC and LL Cool J.",
  "Holy Cross Cemetery": "One of Brooklyn's historic Catholic cemeteries, operated by the Diocese of Brooklyn since 1849.",
  "Howard Beach-Lindenwood": "A close-knit South Queens community known for its strong Italian American roots and waterfront setting.",
  "Hunts Point": "Once a resort area for wealthy New Yorkers, Hunts Point became one of the Bronx's major industrial zones.",
  "Hutchinson Metro Center": "A mixed-use commercial district in the Bronx built on former parkland along the Hutchinson River Parkway.",
  "Inwood": "Home to Manhattan's last remaining old-growth forest, Inwood Hill Park has trees over 200 years old.",
  "Inwood Hill Park": "The park contains ancient caves once used by the Lenape people long before European settlement.",
  "Jackson Heights": "One of the most linguistically diverse neighborhoods on Earth, with thriving South Asian and Latin American communities.",
  "Jacob Riis Park-Fort Tilden-Breezy Point Tip": "Named for the muckraking journalist who exposed NYC's tenement conditions in his 1890 book How the Other Half Lives.",
  "Jamaica": "Jamaica was one of the earliest English settlements in Queens, established in the 1650s.",
  "Jamaica Bay (East)": "The eastern portion of Jamaica Bay is a vital migratory bird habitat within the Gateway National Recreation Area.",
  "Jamaica Bay (West)": "The western bay waters provide critical habitat for horseshoe crabs, herons, and migratory shorebirds.",
  "Jamaica Estates-Holliswood": "One of Queens' most exclusive residential enclaves, where Donald Trump grew up in a Tudor Revival mansion.",
  "Jamaica Hills-Briarwood": "A diverse Queens neighborhood at the edge of Jamaica's commercial core.",
  "John F. Kennedy International Airport": "Opened in 1948 as Idlewild Airport, JFK became one of the world's busiest international gateways.",
  "Kensington": "A densely populated Brooklyn neighborhood home to large Bangladeshi, Pakistani, and Mexican communities.",
  "Kew Gardens": "Home to Queens Borough Hall since 1940 and a charming Tudor-style commercial strip along Lefferts Boulevard.",
  "Kew Gardens Hills": "A predominantly Orthodox Jewish neighborhood in central Queens developed after World War II.",
  "Kingsbridge Heights-Van Cortlandt Village": "A Bronx neighborhood named for the original bridge over Spuyten Duyvil Creek built in the 1600s.",
  "Kingsbridge-Marble Hill": "Marble Hill is geographically part of the Bronx but politically still belongs to Manhattan borough.",
  "Kissena Park": "The park was home to a 19th-century nursery that supplied trees to parks across New York City.",
  "LaGuardia Airport": "Opened in 1939 and named for NYC mayor Fiorello LaGuardia, who famously refused to fly into Newark.",
  "Laurelton": "A southeastern Queens neighborhood that transitioned from a predominantly white to a Black middle-class community in the 1960s.",
  "Lincoln Terrace Park": "A small but beloved Crown Heights park, also known as Battle Pass Park, with rich neighborhood history.",
  "Long Island City-Hunters Point": "LIC's waterfront offers some of the most dramatic views of the Manhattan skyline in all of NYC.",
  "Longwood": "A South Bronx neighborhood with a rich Puerto Rican cultural heritage and historic row houses.",
  "Lower East Side": "The LES was the primary landing zone for Jewish immigrants from Eastern Europe between 1880 and 1920.",
  "Madison": "A quiet residential area in Brooklyn's Marine Park neighborhood, named after President James Madison.",
  "Manhattanville-West Harlem": "Once a thriving industrial waterfront, Manhattanville is now the site of Columbia University's expanding campus.",
  "Mapleton-Midwood (West)": "A Brooklyn neighborhood with a significant Syrian and Lebanese Jewish community established in the mid-20th century.",
  "Marine Park-Mill Basin-Bergen Beach": "Marine Park is Brooklyn's largest park, home to a nature center and pristine salt marsh.",
  "Marine Park-Plumb Island": "Plumb Beach is a popular fishing and windsurfing spot on the shores of Jamaica Bay.",
  "Mariner's Harbor-Arlington-Graniteville": "A Staten Island neighborhood with a long shipbuilding history dating to the 19th century.",
  "Maspeth": "One of Queens' oldest communities, Maspeth was settled by Dutch colonists in the 1640s.",
  "McGuire Fields": "A former military airfield on Staten Island that served as a training base during World War II.",
  "Melrose": "The South Bronx neighborhood that became synonymous with the hip-hop and graffiti art movements of the 1970s.",
  "Middle Village": "A quiet Queens neighborhood known for its cemeteries, which together contain over a million burials.",
  "Middle Village Cemetery": "The Lutheran Cemetery here has been in continuous use since 1852 and spans over 60 acres.",
  "Midtown South-Flatiron-Union Square": "The iconic Flatiron Building, completed in 1902, was one of the world's first skyscrapers.",
  "Midtown-Times Square": "Times Square was originally named Longacre Square and served as NYC's carriage and horse trade district.",
  "Midwood": "A Brooklyn neighborhood shaped by its large Sephardic Jewish and Pakistani communities.",
  "Miller Field": "A former US Army airfield on Staten Island that hosted early aviation pioneers in the 1920s.",
  "Montefiore Cemetery": "A historic Jewish cemetery in Queens that has been in operation since 1892.",
  "Morningside Heights": "Home to Columbia University, Barnard College, and the Cathedral of Saint John the Divine.",
  "Morris Park": "A Bronx neighborhood named for the 19th-century racetrack that once drew crowds from across the city.",
  "Morrisania": "One of the Bronx's oldest communities, Morrisania was a separate town before being annexed in 1874.",
  "Mott Haven-Port Morris": "Mott Haven features the nation's highest concentration of children with asthma due to industrial pollution.",
  "Mount Eden-Claremont (West)": "A densely populated Bronx neighborhood shaped by African American and Latino communities over decades.",
  "Mount Hebron & Cedar Grove Cemeteries": "These adjacent Queens cemeteries contain burials dating back to the mid-19th century.",
  "Mount Hope": "A Bronx neighborhood named for the elevated terrain that offers views across the surrounding area.",
  "Mount Olivet & All Faiths Cemeteries": "Queens cemeteries serving diverse religious communities since the late 19th century.",
  "Murray Hill-Broadway Flushing": "The stretch along Northern Boulevard in Flushing that connects downtown to surrounding residential neighborhoods.",
  "Murray Hill-Kips Bay": "The neighborhood was named for Robert Murray, whose farmhouse sat here during the Revolutionary War.",
  "New Dorp-Midland Beach": "New Dorp was one of the original Dutch settlements on Staten Island, founded in the 1600s.",
  "New Springville-Willowbrook-Bulls Head-Travis": "A central Staten Island area that remained largely rural until rapid development in the postwar decades.",
  "North & South Brother Islands": "North Brother Island is where Typhoid Mary was quarantined for much of her life in the early 1900s.",
  "North Corona": "A predominantly Latino neighborhood adjacent to Flushing Meadows Park in the heart of Queens.",
  "Norwood": "A Bronx neighborhood home to the Edgar Allan Poe Cottage, where the writer spent his final years.",
  "Oakland Gardens-Hollis Hills": "One of Queens' quieter residential communities on the Nassau County border.",
  "Oakwood-Richmondtown": "Historic Richmond Town preserves over 25 historic structures depicting life in Staten Island from 1695 onward.",
  "Ocean Hill": "A Brooklyn neighborhood that was the site of a landmark 1968 teachers' strike and school decentralization battle.",
  "Old Astoria-Hallets Point": "Hallets Point sits on a peninsula where the East River's dangerous currents once wrecked countless ships.",
  "Ozone Park": "A diverse South Queens neighborhood home to one of the city's largest Indo-Caribbean communities.",
  "Ozone Park (North)":"The northern section of Ozone Park where Howard Beach transitions into the broader Queens residential grid.",
  "Park Slope": "Park Slope became one of Brooklyn's most desirable neighborhoods after the construction of Prospect Park in 1867.",
  "Parkchester": "A massive planned residential complex in the Bronx, built in 1940 and home to 40,000 residents.",
  "Pelham Bay Park": "At 2,772 acres, Pelham Bay Park is three times the size of Central Park and NYC's largest park.",
  "Pelham Bay-Country Club-City Island": "City Island is a fishing village that feels transplanted from New England into the Bronx.",
  "Pelham Gardens": "A residential Bronx neighborhood developed in the early 20th century along the New Haven rail line.",
  "Pelham Parkway-Van Nest": "The Pelham Parkway was designed by Frederick Law Olmsted Jr. as part of the Bronx parkway system.",
  "Pomonok-Electchester-Hillcrest": "Electchester was built in 1949 as cooperative housing for electrical workers and their families.",
  "Port Richmond": "One of Staten Island's oldest and most diverse commercial districts, with roots in the colonial era.",
  "Prospect Heights": "Home to the Barclays Center arena and adjacent to the Brooklyn Museum and Botanic Garden.",
  "Prospect Lefferts Gardens-Wingate": "A neighborhood known for its beautiful blocks of Romanesque Revival rowhouses from the 1890s.",
  "Prospect Park": "Designed by Olmsted and Vaux, they considered Prospect Park a finer achievement than Central Park.",
  "Queens Village": "A neighborhood straddling the border between urban Queens and the quieter communities near Nassau County.",
  "Queensboro Hill": "A small, dense neighborhood in central Flushing with a large Asian and South Asian community.",
  "Queensbridge-Ravenswood-Dutch Kills": "Queensbridge Houses, built in 1939, is the largest public housing project in the United States.",
  "Randall's Island": "The island connects to all three boroughs and hosts major music festivals including Governors Ball.",
  "Rego Park": "Named for the Real Good Construction Company that built the neighborhood in the 1920s.",
  "Richmond Hill": "A South Queens neighborhood with one of the largest Sikh communities in the eastern United States.",
  "Ridgewood": "Straddling the Brooklyn-Queens border, Ridgewood has some of the finest Romanesque Revival rowhouses in NYC.",
  "Rikers Island": "New York City's main jail complex has operated on this island in the East River since 1932.",
  "Riverdale-Spuyten Duyvil": "Riverdale is one of NYC's wealthiest neighborhoods, featuring estates, mansions, and sweeping Hudson River views.",
  "Rockaway Beach-Arverne-Edgemere": "The Rockaways offered the only Atlantic Ocean beach accessible by subway in all of New York City.",
  "Rockaway Community Park": "A natural area on the Rockaway Peninsula used for passive recreation and environmental restoration.",
  "Rosebank-Shore Acres-Park Hill": "Rosebank was home to sculptor Frederick MacMonnies and painter Alice Austen, one of America's earliest photographers.",
  "Rosedale": "A southeastern Queens community that became a desirable destination for middle-class Black families in the 1970s.",
  "Sheepshead Bay-Manhattan Beach-Gerritsen Beach": "Sheepshead Bay was named for the sheepshead fish once abundant in its waters.",
  "Shirley Chisholm State Park": "Named for Brooklyn's own Shirley Chisholm, the first Black woman elected to Congress in 1968.",
  "Snug Harbor": "Built in 1833 as a retirement home for sailors, Snug Harbor is now a cultural center.",
  "SoHo-Little Italy-Hudson Square": "SoHo contains the largest collection of cast-iron architecture in the world, built between 1850 and 1880.",
  "Soundview Park": "A Bronx waterfront park along the East River offering views of the Sound and Throgs Neck Bridge.",
  "Soundview-Bruckner-Bronx River": "The Bronx River runs through this neighborhood and is the only freshwater river in NYC.",
  "Soundview-Clason Point": "Clason Point was once a popular beach resort before industrial development transformed the South Bronx waterfront.",
  "South Jamaica": "A South Queens neighborhood with deep roots in African American working-class history and community organizing.",
  "South Ozone Park": "A diverse Queens neighborhood adjacent to JFK Airport with large Guyanese and Trinidadian communities.",
  "South Richmond Hill": "A Queens neighborhood known for its large Indo-Guyanese community and vibrant religious and cultural life.",
  "South Williamsburg": "The center of one of NYC's largest Hasidic Jewish communities, the Satmar sect settled here after WWII.",
  "Spring Creek Park": "A protected wetland and park in East New York adjacent to Jamaica Bay.",
  "Spring Creek-Starrett City": "Starrett City, now called Spring Creek Towers, was one of the nation's largest subsidized housing complexes.",
  "Springfield Gardens (North)-Rochdale Village": "Rochdale Village, built in 1963, was a pioneering integrated cooperative housing development in Southeast Queens.",
  "Springfield Gardens (South)-Brookville": "A residential Queens community at the edge of the city, bordering Nassau County to the east.",
  "St. Albans": "A proudly African American middle-class neighborhood and home of jazz legends Count Basie and John Coltrane.",
  "St. George-New Brighton": "St. George is the Staten Island Ferry terminal, a gateway that has welcomed visitors since 1905.",
  "St. John Cemetery": "A Queens cemetery operated by the Roman Catholic Diocese of Brooklyn since 1879.",
  "St. Michael's Cemetery": "A historic Queens cemetery established in 1852 and one of the oldest in the borough.",
  "Stuyvesant Town-Peter Cooper Village": "Built in 1947 by MetLife, Stuy Town was designed as affordable housing for returning WWII veterans.",
  "Sunnyside": "Sunnyside Gardens, built in 1924, was one of America's first planned garden communities.",
  "Sunnyside Yards (North)": "The vast rail yards here are among the largest in the country and may be redeveloped in coming decades.",
  "Sunnyside Yards (South)": "The southern edge of the sprawling Amtrak and Long Island Rail Road yards that span central Queens.",
  "Sunset Park (Central)": "A Brooklyn neighborhood with thriving Chinese and Latino commercial strips running parallel through the community.",
  "Sunset Park (East)-Borough Park (West)": "A transitional zone between Sunset Park's diverse community and the Orthodox Jewish enclave of Borough Park.",
  "Sunset Park (West)": "The waterfront Industry City complex was once the Bush Terminal, a massive industrial port facility built in 1895.",
  "The Battery-Governors Island-Ellis Island-Liberty Island": "Over 12 million immigrants passed through Ellis Island between 1892 and 1954, the peak era of US immigration.",
  "The Evergreens Cemetery": "A 225-acre Brooklyn cemetery established in 1849 and the resting place of over 500,000 people.",
  "Throgs Neck-Schuylerville": "The Throgs Neck Bridge, opened in 1961, connects the Bronx to Queens across the East River.",
  "Todt Hill-Emerson Hill-Lighthouse Hill-Manor Heights": "At 410 feet, Todt Hill is the highest natural point in New York City south of Maine.",
  "Tompkinsville-Stapleton-Clifton-Fox Hills": "Stapleton was the commercial and social center of Staten Island's North Shore in the 19th century.",
  "Tottenville-Charleston": "Tottenville is NYC's southernmost community, closer to New Jersey than to Manhattan.",
  "Tremont": "A Bronx neighborhood whose main commercial avenue was once a bustling shopping destination for the entire borough.",
  "Tribeca-Civic Center": "Tribeca's enormous loft buildings were converted from industrial warehouses into luxury residences beginning in the 1970s.",
  "United Nations": "The UN headquarters, completed in 1952, occupies land that was formerly a slaughterhouse district along the East River.",
  "University Heights (North)-Fordham": "Fordham University's Rose Hill campus features a botanical garden and Gothic Revival architecture dating to 1841.",
  "University Heights (South)-Morris Heights": "A Bronx neighborhood named for Gouverneur Morris, a Founding Father whose estate once occupied this land.",
  "Upper East Side-Carnegie Hill": "Carnegie Hill takes its name from industrialist Andrew Carnegie, who built his mansion here in 1901.",
  "Upper East Side-Lenox Hill-Roosevelt Island": "Roosevelt Island's tram, opened in 1976, was the first commuter aerial tramway in North America.",
  "Upper East Side-Yorkville": "Yorkville was a hub of German and Central European immigrant life in the late 19th century.",
  "Upper West Side (Central)": "The Dakota, built in 1884, was NYC's first luxury apartment building and John Lennon's home until 1980.",
  "Upper West Side-Lincoln Square": "Lincoln Center for the Performing Arts was built in the 1960s, displacing a neighborhood of 7,000 families.",
  "Upper West Side-Manhattan Valley": "Manhattan Valley is a transitional neighborhood between the Upper West Side and Harlem along the 100s.",
  "Van Cortlandt Park": "NYC's third-largest park contains the oldest public golf course in the United States, opened in 1895.",
  "Wakefield-Woodlawn": "The northernmost neighborhood in the Bronx, bordering Yonkers with a strong African American and Caribbean community.",
  "Washington Heights (North)": "The northern Heights is home to one of the largest Dominican communities in the United States.",
  "Washington Heights (South)": "Home to the Morris-Jumel Mansion, the oldest surviving house in Manhattan, built in 1765.",
  "West Farms": "West Farms was an independent village in the Bronx until it was annexed by NYC in 1895.",
  "West New Brighton-Silver Lake-Grymes Hill": "Grymes Hill is one of Staten Island's most elevated neighborhoods with sweeping views of New York Harbor.",
  "West Village": "The West Village's irregular street grid dates to the 17th century, confusing newcomers ever since.",
  "Westchester Square": "An old Bronx village center with a history stretching back to the colonial era of the 1600s.",
  "Westerleigh-Castleton Corners": "Westerleigh was founded in 1887 as a temperance community where alcohol was strictly prohibited.",
  "Whitestone-Beechhurst": "The Whitestone Bridge, opened in 1939, is one of the most elegant suspension bridges in the US.",
  "Williamsbridge-Olinville": "A Bronx neighborhood with deep roots in African American community life and residential stability.",
  "Williamsburg": "Williamsburg's waterfront warehouses and factories transformed into the center of Brooklyn's arts scene in the 1990s.",
  "Windsor Terrace-South Slope": "A quiet Brooklyn neighborhood between Prospect Park and Greenwood Cemetery with a strong Irish heritage.",
  "Woodhaven": "The former Eldorado amusement park here operated from 1906 to 1939 before being demolished.",
  "Woodlawn Cemetery": "A National Historic Landmark, Woodlawn contains elaborate mausoleums of Gilded Age tycoons including Jay Gould.",
  "Woodside": "A Queens neighborhood with one of the city's largest Filipino communities alongside Irish and Latin American residents.",
  "Yankee Stadium-Macombs Dam Park": "The original Yankee Stadium, built in 1923, was called the House That Ruth Built after Babe Ruth.",
};
